--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "ui/LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to
-- get a callback function in creating scene process.
-- the returned callback function will be registered to
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Panel
local Panel = ccui.Layout:create()
Panel:ignoreContentAdaptWithSize(false)
Panel:setClippingEnabled(false)
Panel:setBackGroundColorType(1)
Panel:setBackGroundColor({r = 127, g = 127, b = 127})
Panel:setBackGroundColorOpacity(85)
Panel:setTouchEnabled(true);
Panel:setLayoutComponentEnabled(true)
Panel:setName("Panel")
Panel:setTag(114)
Panel:setCascadeColorEnabled(true)
Panel:setCascadeOpacityEnabled(true)
Panel:setPosition(-0.8651, -4.7662)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel)
layout:setPositionPercentX(-0.0008)
layout:setPositionPercentY(-0.0062)
layout:setPercentWidth(0.9979)
layout:setPercentHeight(1.0055)
layout:setSize({width = 1021.8240, height = 772.1896})
layout:setLeftMargin(-0.8651)
layout:setRightMargin(3.0414)
layout:setTopMargin(0.5766)
layout:setBottomMargin(-4.7662)
Scene:addChild(Panel)

--Create back
local back = cc.Sprite:create("UIRes/ui_n/000132.png")
back:setName("back")
back:setTag(13)
back:setCascadeColorEnabled(true)
back:setCascadeOpacityEnabled(true)
back:setAnchorPoint(0.0000, 0.0000)
back:setPosition(278.1890, 293.0546)
layout = ccui.LayoutComponent:bindLayoutComponent(back)
layout:setPositionPercentX(0.2717)
layout:setPositionPercentY(0.3816)
layout:setPercentWidth(0.4805)
layout:setPercentHeight(0.2630)
layout:setSize({width = 492.0000, height = 202.0000})
layout:setLeftMargin(278.1890)
layout:setRightMargin(253.8110)
layout:setTopMargin(272.9454)
layout:setBottomMargin(293.0546)
back:setBlendFunc({src = 1, dst = 771})
Scene:addChild(back)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(false)
Text_1:setFontName("")
Text_1:setFontSize(16)
Text_1:setString([[无阿斯顿撒旦撒打死打死打伤打出发啊大大]])
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setTag(14)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setAnchorPoint(1.1833, 0.5874)
Text_1:setPosition(518.1423, 114.7265)
Text_1:setTextColor({r = 230, g = 220, b = 169})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentX(1.0531)
layout:setPositionPercentY(0.5680)
layout:setPercentWidth(0.8130)
layout:setPercentHeight(0.5446)
layout:setSize({width = 400.0000, height = 110.0000})
layout:setLeftMargin(44.8223)
layout:setRightMargin(47.1777)
layout:setTopMargin(41.8875)
layout:setBottomMargin(50.1125)
back:addChild(Text_1)

--Create sureBtn
local sureBtn = ccui.Button:create()
sureBtn:ignoreContentAdaptWithSize(false)
sureBtn:loadTextureNormal("UIRes/Status/000033.png",0)
sureBtn:loadTexturePressed("UIRes/Status/000031.png",0)
sureBtn:loadTextureDisabled("UIRes/Status/000033.png",0)
sureBtn:setTitleFontName("")
sureBtn:setTitleFontSize(14)
sureBtn:setTitleText("确定")
sureBtn:setTitleColor({r = 243, g = 226, b = 149})
sureBtn:setScale9Enabled(true)
sureBtn:setCapInsets({x = 15, y = 6, width = 26, height = 8})
sureBtn:setLayoutComponentEnabled(true)
sureBtn:setName("sureBtn")
sureBtn:setTag(15)
sureBtn:setCascadeColorEnabled(true)
sureBtn:setCascadeOpacityEnabled(true)
sureBtn:setPosition(161.7545, 34.0520)
layout = ccui.LayoutComponent:bindLayoutComponent(sureBtn)
layout:setPositionPercentX(0.3288)
layout:setPositionPercentY(0.1686)
layout:setPercentWidth(0.1138)
layout:setPercentHeight(0.0990)
layout:setSize({width = 56.0000, height = 20.0000})
layout:setLeftMargin(133.7545)
layout:setRightMargin(302.2455)
layout:setTopMargin(157.9480)
layout:setBottomMargin(24.0520)
back:addChild(sureBtn)

--Create cancelBtn
local cancelBtn = ccui.Button:create()
cancelBtn:ignoreContentAdaptWithSize(false)
cancelBtn:loadTextureNormal("UIRes/Status/000033.png",0)
cancelBtn:loadTexturePressed("UIRes/Status/000031.png",0)
cancelBtn:loadTextureDisabled("UIRes/Status/000033.png",0)
cancelBtn:setTitleFontName("")
cancelBtn:setTitleFontSize(14)
cancelBtn:setTitleText("取消")
cancelBtn:setTitleColor({r = 243, g = 226, b = 149})
cancelBtn:setScale9Enabled(true)
cancelBtn:setCapInsets({x = 15, y = 6, width = 26, height = 8})
cancelBtn:setLayoutComponentEnabled(true)
cancelBtn:setName("cancelBtn")
cancelBtn:setTag(113)
cancelBtn:setCascadeColorEnabled(true)
cancelBtn:setCascadeOpacityEnabled(true)
cancelBtn:setPosition(331.7545, 34.0520)
layout = ccui.LayoutComponent:bindLayoutComponent(cancelBtn)
layout:setPositionPercentX(0.6743)
layout:setPositionPercentY(0.1686)
layout:setPercentWidth(0.1138)
layout:setPercentHeight(0.0990)
layout:setSize({width = 56.0000, height = 20.0000})
layout:setLeftMargin(303.7545)
layout:setRightMargin(132.2455)
layout:setTopMargin(157.9480)
layout:setBottomMargin(24.0520)
back:addChild(cancelBtn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()

result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

