--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "ui/LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to
-- get a callback function in creating scene process.
-- the returned callback function will be registered to
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create back
local back = cc.Sprite:create("UIRes/ui1/000460.png")
back:setName("back")
back:setTag(38)
back:setCascadeColorEnabled(true)
back:setCascadeOpacityEnabled(true)
back:setAnchorPoint(0.5120, 0.5000)
back:setPosition(231.2883, 131.7844)
layout = ccui.LayoutComponent:bindLayoutComponent(back)
layout:setPositionPercentX(0.2259)
layout:setPositionPercentY(0.1716)
layout:setPercentWidth(0.4414)
layout:setPercentHeight(0.3359)
layout:setSize({width = 452.0000, height = 258.0000})
layout:setLeftMargin(-0.1546)
layout:setRightMargin(572.1546)
layout:setTopMargin(507.2156)
layout:setBottomMargin(2.7844)
back:setBlendFunc({src = 1, dst = 771})
Scene:addChild(back)

--Create ListView
local ListView = RichText:new()
--ListView:setDirection(1)
--ListView:setGravity(0)
ListView:ignoreContentAdaptWithSize(false)
ListView:setClippingEnabled(false)
ListView:setBackGroundColorOpacity(102)
ListView:setTouchEnabled(true);
ListView:setLayoutComponentEnabled(true)
ListView:setName("ListView")
ListView:setTag(39)
ListView:setCascadeColorEnabled(true)
ListView:setCascadeOpacityEnabled(true)
ListView:setPosition(19.2961, 14.7636)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView)
layout:setPositionPercentX(0.0188)
layout:setPositionPercentY(0.0192)
layout:setPercentWidth(0.4053)
layout:setPercentHeight(0.2994)
layout:setSize({width = 414.9907, height = 229.9355})
layout:setLeftMargin(19.2961)
layout:setRightMargin(589.7131)
layout:setTopMargin(523.3009)
layout:setBottomMargin(14.7636)
Scene:addChild(ListView)

--Create closeBtn
local closeBtn = ccui.Button:create()
closeBtn:ignoreContentAdaptWithSize(false)
closeBtn:loadTextureNormal("UIRes/Button/000003.png",0)
closeBtn:loadTexturePressed("UIRes/Button/000005.png",0)
closeBtn:loadTextureDisabled("UIRes/Button/000003.png",0)
closeBtn:setTitleFontSize(14)
closeBtn:setTitleColor({r = 65, g = 65, b = 70})
closeBtn:setScale9Enabled(true)
closeBtn:setCapInsets({x = 8, y = 11, width = 9, height = 3})
closeBtn:setLayoutComponentEnabled(true)
closeBtn:setName("closeBtn")
closeBtn:setTag(40)
closeBtn:setCascadeColorEnabled(true)
closeBtn:setCascadeOpacityEnabled(true)
closeBtn:setPosition(458.8801, 243.1236)
layout = ccui.LayoutComponent:bindLayoutComponent(closeBtn)
layout:setPositionPercentX(0.4218)
layout:setPositionPercentY(0.3166)
layout:setPercentWidth(0.0244)
layout:setPercentHeight(0.0326)
layout:setSize({width = 25.0000, height = 25.0000})
layout:setLeftMargin(419.3801)
layout:setRightMargin(579.6199)
layout:setTopMargin(512.3765)
layout:setBottomMargin(230.6236)
Scene:addChild(closeBtn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()

result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

