--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "ui/LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to
-- get a callback function in creating scene process.
-- the returned callback function will be registered to
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
result['Layer']=cc.Node:create()
result['Layer']:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(result['Layer'])
layout:setSize({width = 800.0000, height = 600.0000})

--Create Panel_1
result['Panel_1'] = ccui.Layout:create()
result['Panel_1']:ignoreContentAdaptWithSize(false)
result['Panel_1']:setClippingEnabled(false)
result['Panel_1']:setBackGroundColorType(1)
result['Panel_1']:setBackGroundColor({r = 0, g = 0, b = 0})
result['Panel_1']:setTouchEnabled(true);
result['Panel_1']:setLayoutComponentEnabled(true)
result['Panel_1']:setName("Panel_1")
result['Panel_1']:setTag(19)
result['Panel_1']:setCascadeColorEnabled(true)
result['Panel_1']:setCascadeOpacityEnabled(true)
result['Panel_1']:setPosition(5.1680, 0.1391)
result['Panel_1']:setScaleX(3.2250)
result['Panel_1']:setScaleY(1.3119)
layout = ccui.LayoutComponent:bindLayoutComponent(result['Panel_1'])
layout:setPositionPercentX(0.0065)
layout:setPositionPercentY(0.0002)
layout:setPercentWidth(0.2500)
layout:setPercentHeight(0.3333)
layout:setSize({width = 250.0000, height = 200.0000})
layout:setLeftMargin(5.1680)
layout:setRightMargin(594.8320)
layout:setTopMargin(399.8609)
layout:setBottomMargin(0.1391)
result['Layer']:addChild(result['Panel_1'])

--Create posX
local posX = et.MyTextField:create(result['Layer'], "x", "fonts/blackSingle.ttf", 25);
posX:setTextPosition(368.5878, 82.5666);
posX:setTextName("posX");
posX:setLocalZOrder(100000);
posX:setMaxLineWidth(170);
posX:setColor(255, 255, 255);

--Create Text_1
result['Text_1'] = ccui.Text:create()
result['Text_1']:ignoreContentAdaptWithSize(true)
result['Text_1']:setTextAreaSize({width = 0, height = 0})
result['Text_1']:setFontSize(20)
result['Text_1']:setString([[新位置]])
result['Text_1']:setLayoutComponentEnabled(true)
result['Text_1']:setName("Text_1")
result['Text_1']:setTag(15)
result['Text_1']:setCascadeColorEnabled(true)
result['Text_1']:setCascadeOpacityEnabled(true)
result['Text_1']:setAnchorPoint(0.6791, 1.8878)
result['Text_1']:setPosition(344.3543, 134.8468)
result['Text_1']:setScaleX(1.0000)
result['Text_1']:setScaleY(1.1131)
layout = ccui.LayoutComponent:bindLayoutComponent(result['Text_1'])
layout:setPositionPercentX(0.4304)
layout:setPositionPercentY(0.2247)
layout:setPercentWidth(0.0625)
layout:setPercentHeight(0.0333)
layout:setSize({width = 50.0000, height = 20.0000})
layout:setLeftMargin(310.3993)
layout:setRightMargin(439.6007)
layout:setTopMargin(482.9092)
layout:setBottomMargin(97.0908)
result['Layer']:addChild(result['Text_1'])

--Create ChangePosBtn
result['ChangePosBtn'] = ccui.Button:create()
result['ChangePosBtn']:ignoreContentAdaptWithSize(false)
result['ChangePosBtn']:loadTextureNormal("Default/Button_Normal.png",0)
result['ChangePosBtn']:loadTexturePressed("Default/Button_Press.png",0)
result['ChangePosBtn']:loadTextureDisabled("Default/Button_Disable.png",0)
result['ChangePosBtn']:setTitleFontSize(14)
result['ChangePosBtn']:setTitleText("换位置")
result['ChangePosBtn']:setTitleColor({r = 230, g = 230, b = 250})
result['ChangePosBtn']:setScale9Enabled(true)
result['ChangePosBtn']:setCapInsets({x = 15, y = 11, width = 16, height = 14})
result['ChangePosBtn']:setLayoutComponentEnabled(true)
result['ChangePosBtn']:setName("ChangePosBtn")
result['ChangePosBtn']:setTag(17)
result['ChangePosBtn']:setCascadeColorEnabled(true)
result['ChangePosBtn']:setCascadeOpacityEnabled(true)
result['ChangePosBtn']:setAnchorPoint(-0.4101, 0.5443)
result['ChangePosBtn']:setPosition(330.9854, 61.5525)
layout = ccui.LayoutComponent:bindLayoutComponent(result['ChangePosBtn'])
layout:setPositionPercentX(0.4137)
layout:setPositionPercentY(0.1026)
layout:setPercentWidth(0.1225)
layout:setPercentHeight(0.0583)
layout:setSize({width = 98.0000, height = 35.0000})
layout:setLeftMargin(371.1774)
layout:setRightMargin(330.8226)
layout:setTopMargin(522.4982)
layout:setBottomMargin(42.5018)
result['Layer']:addChild(result['ChangePosBtn'])


result['beginMoveBtn'] = ccui.Button:create()
result['beginMoveBtn']:ignoreContentAdaptWithSize(false)
result['beginMoveBtn']:loadTextureNormal("Default/Button_Normal.png",0)
result['beginMoveBtn']:loadTexturePressed("Default/Button_Press.png",0)
result['beginMoveBtn']:loadTextureDisabled("Default/Button_Disable.png",0)
result['beginMoveBtn']:setTitleFontSize(14)
result['beginMoveBtn']:setTitleText("开启移动")
result['beginMoveBtn']:setTitleColor({r = 230, g = 230, b = 250})
result['beginMoveBtn']:setScale9Enabled(true)
result['beginMoveBtn']:setCapInsets({x = 15, y = 11, width = 16, height = 14})
result['beginMoveBtn']:setLayoutComponentEnabled(true)
result['beginMoveBtn']:setName("beginMoveBtn")
result['beginMoveBtn']:setTag(17)
result['beginMoveBtn']:setCascadeColorEnabled(true)
result['beginMoveBtn']:setCascadeOpacityEnabled(true)
result['beginMoveBtn']:setAnchorPoint(-0.4101, 0.5443)
result['beginMoveBtn']:setPosition(330.9854, 140.5525)
layout = ccui.LayoutComponent:bindLayoutComponent(result['beginMoveBtn'])
layout:setPositionPercentX(0.4137)
layout:setPositionPercentY(0.1026)
layout:setPercentWidth(0.1225)
layout:setPercentHeight(0.0583)
layout:setSize({width = 98.0000, height = 35.0000})
layout:setLeftMargin(371.1774)
layout:setRightMargin(330.8226)
layout:setTopMargin(522.4982)
layout:setBottomMargin(42.5018)
result['Layer']:addChild(result['beginMoveBtn'])

--Create AddMonBtn
result['AddMonBtn'] = ccui.Button:create()
result['AddMonBtn']:ignoreContentAdaptWithSize(false)
result['AddMonBtn']:loadTextureNormal("Default/Button_Normal.png",0)
result['AddMonBtn']:loadTexturePressed("Default/Button_Press.png",0)
result['AddMonBtn']:loadTextureDisabled("Default/Button_Disable.png",0)
result['AddMonBtn']:setTitleFontSize(14)
result['AddMonBtn']:setTitleText("添加怪物")
result['AddMonBtn']:setTitleColor({r = 230, g = 230, b = 250})
result['AddMonBtn']:setScale9Enabled(true)
result['AddMonBtn']:setCapInsets({x = 15, y = 11, width = 16, height = 14})
result['AddMonBtn']:setLayoutComponentEnabled(true)
result['AddMonBtn']:setName("AddMonBtn")
result['AddMonBtn']:setTag(18)
result['AddMonBtn']:setCascadeColorEnabled(true)
result['AddMonBtn']:setCascadeOpacityEnabled(true)
result['AddMonBtn']:setPosition(57.5142, 67.0398)
layout = ccui.LayoutComponent:bindLayoutComponent(result['AddMonBtn'])
layout:setPositionPercentX(0.0719)
layout:setPositionPercentY(0.1117)
layout:setPercentWidth(0.1225)
layout:setPercentHeight(0.0583)
layout:setSize({width = 98.0000, height = 35.0000})
layout:setLeftMargin(8.5142)
layout:setRightMargin(693.4858)
layout:setTopMargin(515.4602)
layout:setBottomMargin(49.5398)
result['Layer']:addChild(result['AddMonBtn'])

--Create SaveBtn
result['SaveBtn'] = ccui.Button:create()
result['SaveBtn']:ignoreContentAdaptWithSize(false)
result['SaveBtn']:loadTextureNormal("Default/Button_Normal.png",0)
result['SaveBtn']:loadTexturePressed("Default/Button_Press.png",0)
result['SaveBtn']:loadTextureDisabled("Default/Button_Disable.png",0)
result['SaveBtn']:setTitleFontSize(14)
result['SaveBtn']:setTitleText("保存")
result['SaveBtn']:setTitleColor({r = 230, g = 230, b = 250})
result['SaveBtn']:setScale9Enabled(true)
result['SaveBtn']:setCapInsets({x = 15, y = 11, width = 16, height = 14})
result['SaveBtn']:setLayoutComponentEnabled(true)
result['SaveBtn']:setName("SaveBtn")
result['SaveBtn']:setTag(20)
result['SaveBtn']:setCascadeColorEnabled(true)
result['SaveBtn']:setCascadeOpacityEnabled(true)
result['SaveBtn']:setAnchorPoint(-0.4522, -0.0791)
result['SaveBtn']:setPosition(131.1804, 45.4107)
layout = ccui.LayoutComponent:bindLayoutComponent(result['SaveBtn'])
layout:setPositionPercentX(0.1640)
layout:setPositionPercentY(0.0757)
layout:setPercentWidth(0.1225)
layout:setPercentHeight(0.0583)
layout:setSize({width = 98.0000, height = 35.0000})
layout:setLeftMargin(175.4921)
layout:setRightMargin(526.5079)
layout:setTopMargin(516.8199)
layout:setBottomMargin(48.1801)
result['Layer']:addChild(result['SaveBtn'])

--Create InfoText
result['InfoText'] = ccui.Text:create()
result['InfoText']:ignoreContentAdaptWithSize(false)
result['InfoText']:setFontSize(20)
result['InfoText']:setString([[]])
result['InfoText']:enableShadow({r = 110, g = 110, b = 110, a = 255}, {width = 1, height = 1}, 0)
result['InfoText']:setLayoutComponentEnabled(true)
result['InfoText']:setName("InfoText")
result['InfoText']:setTag(21)
result['InfoText']:setCascadeColorEnabled(true)
result['InfoText']:setCascadeOpacityEnabled(true)
result['InfoText']:setPosition(279.6738, 15.1025)
layout = ccui.LayoutComponent:bindLayoutComponent(result['InfoText'])
layout:setPositionPercentX(0.3496)
layout:setPositionPercentY(0.0252)
layout:setPercentWidth(0.6875)
layout:setPercentHeight(0.0333)
layout:setSize({width = 550.0000, height = 20.0000})
layout:setLeftMargin(4.6738)
layout:setRightMargin(245.3262)
layout:setTopMargin(574.8975)
layout:setBottomMargin(5.1025)
result['Layer']:addChild(result['InfoText'])

--Create AiText
local AiText = et.MyTextField:create(result['Layer'], "Monster ai script", "fonts/blackSingle.ttf", 25);
AiText:setTextPosition(100.0305, 160.8007);
AiText:setTextName("AiText");
AiText:setLocalZOrder(100000);
AiText:setMaxLineWidth(170);
AiText:setColor(255, 255, 255);

--Create ReviveText
local ReviveText = et.MyTextField:create(result['Layer'], "Monster revive time", "fonts/blackSingle.ttf", 25);
ReviveText:setTextPosition(104.6998, 126.7331);
ReviveText:setTextName("ReviveText");
ReviveText:setLocalZOrder(100000);
ReviveText:setMaxLineWidth(170);
ReviveText:setColor(255, 255, 255);

--Create AlertAreaText
local AlertAreaText = et.MyTextField:create(result['Layer'], "alert range", "fonts/blackSingle.ttf", 25);
AlertAreaText:setTextPosition(106.1059, 85.7368);
AlertAreaText:setTextName("AlertAreaText");
AlertAreaText:setLocalZOrder(100000);
AlertAreaText:setMaxLineWidth(170);
AlertAreaText:setColor(255, 255, 255);

--Create ai
result['ai'] = ccui.Text:create()
result['ai']:ignoreContentAdaptWithSize(false)
result['ai']:setFontSize(20)
result['ai']:setString([[怪物ai:]])
result['ai']:setLayoutComponentEnabled(true)
result['ai']:setName("ai")
result['ai']:setTag(27)
result['ai']:setCascadeColorEnabled(true)
result['ai']:setCascadeOpacityEnabled(true)
result['ai']:setAnchorPoint(0.4525, 0.4232)
result['ai']:setPosition(37.6377, 179.4807)
layout = ccui.LayoutComponent:bindLayoutComponent(result['ai'])
layout:setPositionPercentX(0.0470)
layout:setPositionPercentY(0.2991)
layout:setPercentWidth(0.0875)
layout:setPercentHeight(0.0412)
layout:setSize({width = 70.0000, height = 24.7147})
layout:setLeftMargin(5.9627)
layout:setRightMargin(724.0374)
layout:setTopMargin(406.2639)
layout:setBottomMargin(169.0214)
result['Layer']:addChild(result['ai'])

--Create Text_2_1
result['Text_2_1'] = ccui.Text:create()
result['Text_2_1']:ignoreContentAdaptWithSize(false)
result['Text_2_1']:setFontSize(20)
result['Text_2_1']:setString([[复活时间:]])
result['Text_2_1']:setLayoutComponentEnabled(true)
result['Text_2_1']:setName("Text_2_1")
result['Text_2_1']:setTag(28)
result['Text_2_1']:setCascadeColorEnabled(true)
result['Text_2_1']:setCascadeOpacityEnabled(true)
result['Text_2_1']:setAnchorPoint(0.4525, 0.4232)
result['Text_2_1']:setPosition(47.6316, 145.4912)
layout = ccui.LayoutComponent:bindLayoutComponent(result['Text_2_1'])
layout:setPositionPercentX(0.0595)
layout:setPositionPercentY(0.2425)
layout:setPercentWidth(0.1125)
layout:setPercentHeight(0.0333)
layout:setSize({width = 90.0000, height = 20.0000})
layout:setLeftMargin(6.9066)
layout:setRightMargin(703.0934)
layout:setTopMargin(442.9728)
layout:setBottomMargin(137.0272)
result['Layer']:addChild(result['Text_2_1'])

--Create Text_2_2
result['Text_2_2'] = ccui.Text:create()
result['Text_2_2']:ignoreContentAdaptWithSize(false)
result['Text_2_2']:setFontSize(20)
result['Text_2_2']:setString([[视野:]])
result['Text_2_2']:setLayoutComponentEnabled(true)
result['Text_2_2']:setName("Text_2_2")
result['Text_2_2']:setTag(29)
result['Text_2_2']:setCascadeColorEnabled(true)
result['Text_2_2']:setCascadeOpacityEnabled(true)
result['Text_2_2']:setAnchorPoint(0.4525, 0.4232)
result['Text_2_2']:setPosition(46.9445, 106.1813)
layout = ccui.LayoutComponent:bindLayoutComponent(result['Text_2_2'])
layout:setPositionPercentX(0.0587)
layout:setPositionPercentY(0.1770)
layout:setPercentWidth(0.1125)
layout:setPercentHeight(0.0333)
layout:setSize({width = 90.0000, height = 20.0000})
layout:setLeftMargin(6.2195)
layout:setRightMargin(703.7805)
layout:setTopMargin(482.2827)
layout:setBottomMargin(97.7173)
result['Layer']:addChild(result['Text_2_2'])

result['campTitle'] = ccui.Text:create()
result['campTitle']:ignoreContentAdaptWithSize(false)
result['campTitle']:setFontSize(20)
result['campTitle']:setString([[阵营:]])
result['campTitle']:setLayoutComponentEnabled(true)
result['campTitle']:setName("campTitle")
result['campTitle']:setTag(29)
result['campTitle']:setCascadeColorEnabled(true)
result['campTitle']:setCascadeOpacityEnabled(true)
result['campTitle']:setAnchorPoint(0.4525, 0.4232)
result['campTitle']:setPosition(578.1154, 165)
layout = ccui.LayoutComponent:bindLayoutComponent(result['campTitle'])
layout:setPositionPercentX(0.0587)
layout:setPositionPercentY(0.1770)
layout:setPercentWidth(0.1125)
layout:setPercentHeight(0.0333)
layout:setSize({width = 90.0000, height = 20.0000})
layout:setLeftMargin(6.2195)
layout:setRightMargin(703.7805)
layout:setTopMargin(482.2827)
layout:setBottomMargin(97.7173)
result['Layer']:addChild(result['campTitle'])

--Create TargetMapIdText
local campLabel = et.MyTextField:create(result['Layer'], "campLabel", "fonts/blackSingle.ttf", 25);
campLabel:setTextPosition(582.1154, 147.5549);
campLabel:setTextName("campLabel");
campLabel:setLocalZOrder(100000);
campLabel:setMaxLineWidth(170);
campLabel:setColor(255, 255, 255);

--Create Text_8
result['setting'] = ccui.Button:create()
result['setting']:ignoreContentAdaptWithSize(false)
result['setting']:loadTextureNormal("Default/Button_Normal.png",0)
result['setting']:loadTexturePressed("Default/Button_Press.png",0)
result['setting']:loadTextureDisabled("Default/Button_Disable.png",0)
result['setting']:setTitleFontSize(14)
result['setting']:setTitleText("设置出生地")
result['setting']:setTitleColor({r = 230, g = 230, b = 250})
result['setting']:setScale9Enabled(true)
result['setting']:setCapInsets({x = 15, y = 11, width = 16, height = 14})
result['setting']:setLayoutComponentEnabled(true)
result['setting']:setName("setting")
result['setting']:setTag(36)
result['setting']:setCascadeColorEnabled(true)
result['setting']:setCascadeOpacityEnabled(true)
result['setting']:setPosition(645.4230, 50.7233)
layout = ccui.LayoutComponent:bindLayoutComponent(result['setting'])
layout:setPositionPercentX(0.8052)
layout:setPositionPercentY(0.3101)
layout:setPercentWidth(0.1875)
layout:setPercentHeight(0.0333)
layout:setSize({width = 150.0000, height = 20.0000})
layout:setLeftMargin(569.1461)
layout:setRightMargin(80.8539)
layout:setTopMargin(403.9572)
layout:setBottomMargin(176.0428)
result['Layer']:addChild(result['setting'])

----

----

--Create TargetMapPosX
local TargetMapPosX = et.MyTextField:create(result['Layer'], "map x", "fonts/blackSingle.ttf", 25);
TargetMapPosX:setTextPosition(580.2840, 82.0743);
TargetMapPosX:setTextName("TargetMapPosX");
TargetMapPosX:setLocalZOrder(100000);
TargetMapPosX:setMaxLineWidth(170);
TargetMapPosX:setColor(255, 255, 255);



--Create Text_2_0
result['Text_2_0'] = ccui.Text:create()
result['Text_2_0']:ignoreContentAdaptWithSize(false)
result['Text_2_0']:setFontSize(20)
result['Text_2_0']:setString([[传送门新地图位置:]])
result['Text_2_0']:setLayoutComponentEnabled(true)
result['Text_2_0']:setName("Text_2_0")
result['Text_2_0']:setTag(35)
result['Text_2_0']:setCascadeColorEnabled(true)
result['Text_2_0']:setCascadeOpacityEnabled(true)
result['Text_2_0']:setAnchorPoint(0.4525, 0.4232)
result['Text_2_0']:setPosition(609.7509, 126.9989)
layout = ccui.LayoutComponent:bindLayoutComponent(result['Text_2_0'])
layout:setPositionPercentX(0.7622)
layout:setPositionPercentY(0.2117)
layout:setPercentWidth(0.0875)
layout:setPercentHeight(0.0333)
layout:setSize({width = 70.0000, height = 20.0000})
layout:setLeftMargin(578.0759)
layout:setRightMargin(151.9241)
layout:setTopMargin(461.4651)
layout:setBottomMargin(118.5349)
result['Layer']:addChild(result['Text_2_0'])

--Create AddPortalBtn
result['AddPortalBtn'] = ccui.Button:create()
result['AddPortalBtn']:ignoreContentAdaptWithSize(false)
result['AddPortalBtn']:loadTextureNormal("Default/Button_Normal.png",0)
result['AddPortalBtn']:loadTexturePressed("Default/Button_Press.png",0)
result['AddPortalBtn']:loadTextureDisabled("Default/Button_Disable.png",0)
result['AddPortalBtn']:setTitleFontSize(14)
result['AddPortalBtn']:setTitleText("添加传送门")
result['AddPortalBtn']:setTitleColor({r = 230, g = 230, b = 250})
result['AddPortalBtn']:setScale9Enabled(true)
result['AddPortalBtn']:setCapInsets({x = 15, y = 11, width = 16, height = 14})
result['AddPortalBtn']:setLayoutComponentEnabled(true)
result['AddPortalBtn']:setName("AddPortalBtn")
result['AddPortalBtn']:setTag(36)
result['AddPortalBtn']:setCascadeColorEnabled(true)
result['AddPortalBtn']:setCascadeOpacityEnabled(true)
result['AddPortalBtn']:setPosition(645.4230, 50.7233)
layout = ccui.LayoutComponent:bindLayoutComponent(result['AddPortalBtn'])
layout:setPositionPercentX(0.8068)
layout:setPositionPercentY(0.0845)
layout:setPercentWidth(0.1225)
layout:setPercentHeight(0.0583)
layout:setSize({width = 98.0000, height = 35.0000})
layout:setLeftMargin(596.4230)
layout:setRightMargin(105.5770)
layout:setTopMargin(531.7767)
layout:setBottomMargin(33.2233)
result['Layer']:addChild(result['AddPortalBtn'])

result['changeMap'] = ccui.Button:create()
result['changeMap']:ignoreContentAdaptWithSize(false)
result['changeMap']:loadTextureNormal("Default/Button_Normal.png",0)
result['changeMap']:loadTexturePressed("Default/Button_Press.png",0)
result['changeMap']:loadTextureDisabled("Default/Button_Disable.png",0)
result['changeMap']:setTitleFontSize(14)
result['changeMap']:setTitleText("切换当前地图")
result['changeMap']:setTitleColor({r = 230, g = 230, b = 250})
result['changeMap']:setScale9Enabled(true)
result['changeMap']:setCapInsets({x = 15, y = 11, width = 16, height = 14})
result['changeMap']:setLayoutComponentEnabled(true)
result['changeMap']:setName("changeMap")
result['changeMap']:setTag(36)
result['changeMap']:setCascadeColorEnabled(true)
result['changeMap']:setCascadeOpacityEnabled(true)
result['changeMap']:setPosition(780.4230, 50.7233)
layout = ccui.LayoutComponent:bindLayoutComponent(result['changeMap'])
layout:setPositionPercentX(0.8068)
layout:setPositionPercentY(0.0845)
layout:setPercentWidth(0.1225)
layout:setPercentHeight(0.0583)
layout:setSize({width = 98.0000, height = 35.0000})
layout:setLeftMargin(596.4230)
layout:setRightMargin(105.5770)
layout:setTopMargin(531.7767)
layout:setBottomMargin(33.2233)
result['Layer']:addChild(result['changeMap'])

--Create monList
result['monList'] = ccui.ListView:create()
result['monList']:setDirection(1)
result['monList']:setGravity(0)
result['monList']:ignoreContentAdaptWithSize(false)
result['monList']:setClippingEnabled(true)
result['monList']:setBackGroundColorType(1)
result['monList']:setBackGroundColor({r = 150, g = 150, b = 255})
result['monList']:setBackGroundColorOpacity(81)
result['monList']:setLayoutComponentEnabled(true)
result['monList']:setName("monList")
result['monList']:setTag(106)
result['monList']:setCascadeColorEnabled(true)
result['monList']:setCascadeOpacityEnabled(true)
result['monList']:setPosition(3.3022, 208.2042)
layout = ccui.LayoutComponent:bindLayoutComponent(result['monList'])
layout:setPositionPercentX(0.0041)
layout:setPositionPercentY(0.3470)
layout:setPercentWidth(0.1825)
layout:setPercentHeight(0.6483)
layout:setSize({width = 146.0002, height = 388.9991})
layout:setLeftMargin(3.3022)
layout:setRightMargin(650.6976)
layout:setTopMargin(2.7968)
layout:setBottomMargin(208.2042)
result['Layer']:addChild(result['monList'])

--Create mapList
result['mapList'] = ccui.ListView:create()
result['mapList']:setDirection(1)
result['mapList']:setGravity(0)
result['mapList']:ignoreContentAdaptWithSize(false)
result['mapList']:setClippingEnabled(true)
result['mapList']:setBackGroundColorType(1)
result['mapList']:setBackGroundColor({r = 150, g = 150, b = 255})
result['mapList']:setBackGroundColorOpacity(102)
result['mapList']:setLayoutComponentEnabled(true)
result['mapList']:setName("mapList")
result['mapList']:setTag(132)
result['mapList']:setCascadeColorEnabled(true)
result['mapList']:setCascadeOpacityEnabled(true)
result['mapList']:setPosition(641.7336, 212.2382)
layout = ccui.LayoutComponent:bindLayoutComponent(result['mapList'])
layout:setPositionPercentX(0.8022)
layout:setPositionPercentY(0.3537)
layout:setPercentWidth(0.1915)
layout:setPercentHeight(0.6454)
layout:setSize({width = 153.1838, height = 387.2650})
layout:setLeftMargin(641.7336)
layout:setRightMargin(5.0826)
layout:setTopMargin(0.4968)
layout:setBottomMargin(212.2382)
result['Layer']:addChild(result['mapList'])

result['doorList'] = ccui.ListView:create()
result['doorList']:setDirection(1)
result['doorList']:setGravity(0)
result['doorList']:ignoreContentAdaptWithSize(false)
result['doorList']:setClippingEnabled(true)
result['doorList']:setBackGroundColorType(1)
result['doorList']:setBackGroundColor({r = 150, g = 150, b = 255})
result['doorList']:setBackGroundColorOpacity(102)
result['doorList']:setLayoutComponentEnabled(true)
result['doorList']:setName("doorList")
result['doorList']:setTag(132)
result['doorList']:setCascadeColorEnabled(true)
result['doorList']:setCascadeOpacityEnabled(true)
result['doorList']:setPosition(820.7336, 212.2382)
layout = ccui.LayoutComponent:bindLayoutComponent(result['doorList'])
layout:setPositionPercentX(0.8022)
layout:setPositionPercentY(0.3537)
layout:setPercentWidth(0.1915)
layout:setPercentHeight(0.6454)
layout:setSize({width = 153.1838, height = 387.2650})
layout:setLeftMargin(641.7336)
layout:setRightMargin(5.0826)
layout:setTopMargin(0.4968)
layout:setBottomMargin(212.2382)
result['Layer']:addChild(result['doorList'])

--Create TargetMapPosY
local TargetMapPosY = et.MyTextField:create(result['Layer'], "map y", "fonts/blackSingle.ttf", 25);
TargetMapPosY:setTextPosition(720.40, 82.0743);
TargetMapPosY:setTextName("TargetMapPosY");
TargetMapPosY:setLocalZOrder(100000);
TargetMapPosY:setMaxLineWidth(170);
TargetMapPosY:setColor(255, 255, 255);

--Create posY
local posY = et.MyTextField:create(result['Layer'], "y", "fonts/blackSingle.ttf", 25);
posY:setTextPosition(442.5878, 82.5666);
posY:setTextName("posY");
posY:setLocalZOrder(100000);
posY:setMaxLineWidth(170);
posY:setColor(255, 255, 255);

--Create Animation
result['animation'] = ccs.ActionTimeline:create()

result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = result['Layer']
return result;
end

return Result

